In [90]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

In [91]:
X_train = pd.read_csv('../Datasets/Job_X_train.csv')
X_test = pd.read_csv('../Datasets/Job_X_test.csv')
y_train = pd.read_csv('../Datasets/Job_y_train.csv')

In [92]:
X_train

enrollee_id      city  city_development_index gender  \
0             6424   city_75                   0.939   Male   
1            18304   city_64                   0.666   Male   
2            22515  city_103                   0.920   Male   
3            15878   city_16                   0.910   Male   
4            22128  city_103                   0.920   Male   
...            ...       ...                     ...    ...   
10058        28053   city_21                   0.624   Male   
10059        28108  city_103                   0.920   Male   
10060           58   city_21                   0.624   Male   
10061        11305  city_103                   0.920   Male   
10062        21806   city_83                   0.923   Male   

      relevent_experience enrolled_university education_level  \
0                     Has                  No        Graduate   
1                      No                Full            High   
2                      No                Full            High   
3                     Has                  No        Graduate   
4                     Has                  No        Graduate   
...                   ...                 ...             ...   
10058                  No                Full        Graduate   
10059                 Has                  No             Phd   
10060                 Has                Full            High   
10061                  No                Full        Graduate   
10062                 Has                  No        Graduate   

      major_discipline experience company_size         company_type  \
0                 STEM         10        50-99              Pvt Ltd   
1                  NaN          2          NaN                  NaN   
2                  NaN          4          NaN                  NaN   
3                 STEM          8        50-99  Early Stage Startup   
4                 STEM          6       10000+              Pvt Ltd   
...                ...        ...          ...                  ...   
10058             STEM          4          NaN                  NaN   
10059             STEM        >20          NaN                  NaN   
10060              NaN          3          NaN              Pvt Ltd   
10061             STEM          6          NaN                  NaN   
10062             STEM         19          NaN                  NaN   

      last_new_job  training_hours  
0                1             176  
1                1             110  
2            never              44  
3                1              82  
4                1              70  
...            ...             ...  
10058        never              34  
10059            1              72  
10060        never              53  
10061            1             166  
10062           >4              30  

[10063 rows x 13 columns]

In [93]:
X_test

enrollee_id      city  city_development_index gender  \
0             666  city_162                   0.767   Male   
1           28806  city_160                   0.920   Male   
2            5826   city_21                   0.624   Male   
3           19061  city_114                   0.926   Male   
4           28476  city_103                   0.920   Male   
...           ...       ...                     ...    ...   
4308        14257   city_21                   0.624   Male   
4309         6374   city_21                   0.624   Male   
4310        15133  city_160                   0.920   Male   
4311        27018   city_16                   0.910   Male   
4312         7386  city_173                   0.878   Male   

     relevent_experience enrolled_university education_level major_discipline  \
0                    Has                  No         Masters             STEM   
1                    Has                  No            High              NaN   
2                     No                 NaN             NaN              NaN   
3                    Has                  No         Masters             STEM   
4                    Has                  No        Graduate             Arts   
...                  ...                 ...             ...              ...   
4308                  No                Full        Graduate             STEM   
4309                 Has                  No        Graduate  Business Degree   
4310                  No                Part        Graduate             STEM   
4311                 Has                  No        Graduate             STEM   
4312                  No                  No        Graduate       Humanities   

     experience company_size    company_type last_new_job  training_hours  
0           >20        50-99  Funded Startup            4               8  
1             5        50-99  Funded Startup            1              24  
2             2          NaN             NaN        never              24  
3            11      100-500         Pvt Ltd            2              50  
4             5          NaN             NaN            2              72  
...         ...          ...             ...          ...             ...  
4308         13        10/49             NGO            1              21  
4309         14          <10         Pvt Ltd            1              87  
4310          3          NaN             NaN            1             322  
4311          8          <10         Pvt Ltd            3              78  
4312         14          NaN             NaN            1              42  

[4313 rows x 13 columns]

In [94]:
y_train

enrollee_id  target
0             6424       0
1            18304       0
2            22515       0
3            15878       0
4            22128       0
...            ...     ...
10058        28053       1
10059        28108       1
10060           58       1
10061        11305       1
10062        21806       1

[10063 rows x 2 columns]

In [95]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10063 entries, 0 to 10062
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             10063 non-null  int64  
 1   city                    10063 non-null  object 
 2   city_development_index  10063 non-null  float64
 3   gender                  10063 non-null  object 
 4   relevent_experience     10063 non-null  object 
 5   enrolled_university     9921 non-null   object 
 6   education_level         9901 non-null   object 
 7   major_discipline        8740 non-null   object 
 8   experience              10063 non-null  object 
 9   company_size            7133 non-null   object 
 10  company_type            7048 non-null   object 
 11  last_new_job            10063 non-null  object 
 12  training_hours          10063 non-null  int64  
dtypes: float64(1), int64(2), object(10)
memory usage: 1022.1+ KB


In [96]:
X_train.isna().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university        142
education_level            162
major_discipline          1323
experience                   0
company_size              2930
company_type              3015
last_new_job                 0
training_hours               0
dtype: int64

In [97]:
y_train.isna().sum()

enrollee_id    0
target         0
dtype: int64

In [98]:
Enrollee_ID = X_test['enrollee_id'].copy()

X_train = X_train.drop(columns=['enrollee_id', 'major_discipline', 'company_size', 'company_type', 'city'])
X_test = X_test.drop(columns=['enrollee_id', 'major_discipline', 'company_size', 'company_type', 'city'])
y_train = y_train.drop(columns=['enrollee_id'])

In [99]:
X_train['enrolled_university'] = X_train['enrolled_university'].fillna(X_train.enrolled_university.value_counts().idxmax())
X_test['enrolled_university'] = X_test['enrolled_university'].fillna(X_test.enrolled_university.value_counts().idxmax())

X_train['education_level'] = X_train['education_level'].fillna(X_train.education_level.value_counts().idxmax())
X_test['education_level'] = X_test['education_level'].fillna(X_test.education_level.value_counts().idxmax())

In [100]:
X_train.isna().sum()

city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
experience                0
last_new_job              0
training_hours            0
dtype: int64

In [101]:
X_train_cat = X_train.select_dtypes('object').copy()
X_test_cat = X_test.select_dtypes('object').copy()

ohe = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe.fit(X_train_cat)

X_train_ohe = ohe.transform(X_train_cat)
X_test_ohe = ohe.transform(X_test_cat)

X_train_num = X_train.select_dtypes(exclude='object').copy()
X_test_num = X_test.select_dtypes(exclude='object').copy()

scaler = MinMaxScaler()
scaler.fit(X_train_num)

X_train_sca = scaler.transform(X_train_num)
X_test_sca = scaler.transform(X_test_num)

X_TRAIN = np.concatenate([X_train_ohe, X_train_sca], axis=1)
X_TEST = np.concatenate([X_test_ohe, X_test_sca], axis=1)

y_TRAIN = y_train['target']

print(X_TRAIN.shape, X_TEST.shape, y_TRAIN.shape)

xtrain, xtest,ytrain, ytest = train_test_split(X_TRAIN, y_TRAIN, test_size=0.25, stratify=y_TRAIN, random_state=2022)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

def make_models(xtrain, xtest, ytrain, ytest):
    model1 = LogisticRegression(solver='lbfgs', max_iter=1000).fit(xtrain, ytrain)
    print('model1', get_score(model1, xtrain, xtest, ytrain, ytest))
    
    model2 = DecisionTreeClassifier(random_state=2022).fit(xtrain, ytrain)
    print('model2', get_score(model2, xtrain, xtest, ytrain, ytest))
    
    for d in range(3,8):
        model2 = DecisionTreeClassifier(max_depth=d, random_state=2022).fit(xtrain, ytrain)
        print('model2', d, get_score(model2, xtrain, xtest, ytrain, ytest))
    
    model3 = RandomForestClassifier(random_state=2022).fit(xtrain, ytrain)
    print('model3', get_score(model3, xtrain, xtest, ytrain, ytest))
    
    for d in range(3,8):
        model3 = RandomForestClassifier(500, max_depth=d, random_state=2022).fit(xtrain, ytrain)
        print('model3', d, get_score(model3, xtrain, xtest, ytrain, ytest))
    
def get_score(model, xtrain, xtest, ytrain, ytest):
    A = model.score(xtrain, ytrain)
    ypred = model.predict_proba(xtest)[:,1]
    print(model.predict_proba(xtest))
    print('0', model.predict_proba(xtest)[:,0])
    print('1', model.predict_proba(xtest)[:,1])
    B = roc_auc_score(ytest, ypred)
    
    return f'{A:.4} {B:.4}'

make_models(xtrain, xtest, ytrain, ytest)

final_model = LogisticRegression(solver='lbfgs', max_iter=1000).fit(xtrain, ytrain)
print('final_model', get_score(final_model, xtrain, xtest, ytrain, ytest))

y_pred = final_model.predict(X_TEST)
y_pred_proba = final_model.predict_proba(X_TEST)[:,1]

obj = {
    'Enrollee_ID' : Enrollee_ID,
    'target' : y_pred,
    'target_proba' : y_pred_proba
}

result = pd.DataFrame(obj)
result.to_csv('./result.csv', index=False)

(10063, 42) (4313, 42) (10063,)
(7547, 42) (2516, 42) (7547,) (2516,)
[[0.83982682 0.16017318]
 [0.88558221 0.11441779]
 [0.48327889 0.51672111]
 ...
 [0.63019096 0.36980904]
 [0.90784227 0.09215773]
 [0.87676739 0.12323261]]
0 [0.83982682 0.88558221 0.48327889 ... 0.63019096 0.90784227 0.87676739]
1 [0.16017318 0.11441779 0.51672111 ... 0.36980904 0.09215773 0.12323261]
model1 0.7827 0.7318
[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
0 [1. 0. 0. ... 0. 1. 1.]
1 [0. 1. 1. ... 1. 0. 0.]
model2 0.9903 0.6021
[[0.87338501 0.12661499]
 [0.87338501 0.12661499]
 [0.4001938  0.5998062 ]
 ...
 [0.80068729 0.19931271]
 [0.87338501 0.12661499]
 [0.87338501 0.12661499]]
0 [0.87338501 0.87338501 0.4001938  ... 0.80068729 0.87338501 0.87338501]
1 [0.12661499 0.12661499 0.5998062  ... 0.19931271 0.12661499 0.12661499]
model2 3 0.7971 0.7275
[[0.85234094 0.14765906]
 [0.85234094 0.14765906]
 [0.38367347 0.61632653]
 ...
 [0.80344828 0.19655172]
 [0.85234094 0.14765906]
 [0.9032992  0.